server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE

          predicates:
            - Path=/orders/**

          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - GATEWAY_TIMEOUT
                  - INTERNAL_SERVER_ERROR
                methods:
                  - GET
                  - POST

            - name: CircuitBreaker
              args:
                name: orderServiceCB
                fallbackUri: forward:/fallback/orders

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

resilience4j:
  circuitbreaker:
    instances:
      orderServiceCB:
        registerHealthIndicator: true

        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2

        minimumNumberOfCalls: 2
        failureRateThreshold: 50

        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

        automaticTransitionFromOpenToHalfOpenEnabled: true
