server:
  port: 8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:     # ✅ CORRECT PLACE
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**
#              filters:
#                - name: RequestRateLimiter
#                  args:
#                    redis-rate-limiter.replenishRate: 10
#                    redis-rate-limiter.burstCapacity: 20

                - name: Retry
                  args:
                    retries: 2
                    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                    methods: GET, POST

                - name: CircuitBreaker
                  args:
                    name: orderServiceCB
                    fallbackUri: forward:/fallback/orders
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
#resilience4j:
#  circuitbreaker:
#    instances:
#      order-service:
#        failure-rate-threshold: 50
#        sliding-window-size: 10
#        wait-duration-in-open-state: 10s
resilience4j:
  circuitbreaker:
    instances:
      orderServiceCB:
        registerHealthIndicator: true

        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10

        minimumNumberOfCalls: 5

        failureRateThreshold: 50

        waitDurationInOpenState: 10s

        permittedNumberOfCallsInHalfOpenState: 3

        automaticTransitionFromOpenToHalfOpenEnabled: true
